### ISSUE TITLE
git-s3 deploy - The bucket you are attempting to access must be addressed using the specified endpoint

### ISSUE THREAD

**Issue by bedge** [schickling/git-s3#9]
Followed the instructions detailed here: https://github.com/schickling/git-s3/blob/master/doc/EXAMPLE.md

Bucket does exist and credentials are working for all other tools I've tested with.
Full output is:

```
%> ~/.composer/vendor/bin/git-s3 config
Enter your AWS access key ID: XXXXXXXXXXXX
Enter your AWS secret access key: XXXXXXXXXXXXXXXX
Enter your Region name (default: eu-west-1): us-west-2
Enter your bucket title: yyy.yyy.yyy
Enter the path (relative or absolute) where your repo lives: .
Do you want to clone your repo? (default: "n"):
Configuration was successful.

%> ~/.composer/vendor/bin/git-s3 deploy
Uploading aws/admin/git.template

  [Aws\S3\Exception\PermanentRedirectException]
  The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint: "yyy.yyy.yyy.s3.amazonaws.com".

deploy
```

**Comment by brianhu** [comment]
I can reproduce this issue with bucket name containing dot.

**Comment by njcameron** [comment]
Im using s3 for static web hosting so I need the dot. Any idea how I can get it working with dots?

**Comment by heskymatic** [comment]
Same problem when use against a static web hosting bucket

**Comment by arvinkx** [comment]
The issue with dots seems to be due to the region not being specified when the S3Client goes to upload the files. In `src/GitS3/Bucket.php` on line 27 when the `S3Client::factory` method is called, if you add the key `region` with the bucket's region (ex. us-west-1) as the value to the factory method it will work with dots as well. 
```
$this->client = S3Client::factory(array(
				'key'		=> $key,
				'secret'	=> $secret,
				'region'	=> 'us-west-1' // Needed or else buckets with dots will throw an error
			));

```
This is obviously a hack to get it to work, essentially the region needs to be written in to be saved in the config file.

**Comment by heskymatic** [comment]
@arvinkx thanks for the discovery

**Comment by heskymatic** [comment]
https://github.com/schickling/git-s3/pull/14

**Comment by zomerfeld** [comment]
Maybe a dumb question, but how do I resolve this on my computer? Update Git-s3?

**Comment by heskymatic** [comment]
@zomerfeld `composer global update schickling/git-s3:dev-master`

**Comment by zomerfeld** [comment]
Package "schickling/git-s3:dev-master" listed for update is not installed. Ignoring.

But running this:
`$ composer global licenses
```
`Changed current directory to /Users/zomerfeld/.composer
Name: __root__
Version: No version set (parsed as 1.0.0)
Licenses: none
Dependencies:

Name                       Version             License     
aws/aws-sdk-php            2.4.12              Apache-2.0  
cpliakas/git-wrapper       1.0.3               GPL-3.0     
guzzle/guzzle              v3.8.1              MIT         
schickling/git-s3          dev-master f9a16c7  none        
symfony/console            v2.8.1              MIT         
symfony/event-dispatcher   v2.8.1              MIT         
symfony/filesystem         v2.8.1              MIT         
symfony/finder             v2.8.1              MIT         
symfony/polyfill-mbstring  v1.0.1              MIT         
symfony/process            v2.8.1              MIT         
symfony/yaml               v2.8.1              MIT      
```

**Comment by heskymatic** [comment]
f9a16c7 means it's already up to date

**Comment by zomerfeld** [comment]
I'm still getting this issue then: 
` [Aws\S3\Exception\PermanentRedirectException]                                                                                      
  The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this e  
  ndpoint: "zomerfeld.org.s3.amazonaws.com".`

**Comment by zomerfeld** [comment]
Any idea why or other information needed to help resolve it?

**Comment by Irishsmurf** [comment]
Without posting your Access Keys, whats your configuration look like?

**Comment by zomerfeld** [comment]
(with slight modifications):
region: us-east-1
bucket: bucketz.org
path: /Users/igor/Dropbox/Projects/bucketz/bootstrap-3.1.1/dist/

**Comment by zomerfeld** [comment]
Any clues?

**Comment by zomerfeld** [comment]
Just found the solution, looking back on the thread. 
The region was set incorrectly for me - the new bucket I set up was in west-1. 

I guess the error was just a bit misleading!

Thank you!

**Comment by bedge** [comment]
Closing, this is old. Don't use dots in your bucket names and pay attention to your region.
